### PR TITLE
Added French translation

### PR DESCRIPTION
**Pull request by koudjdj**

### CODE REVIEW

**Comment by darkwhispering** [comment]
Sry for the late response. I'll take a look at this soon and merge.

**Comment by darkwhispering** [comment]
I have updated my plugin today and there is a new string added that needs translation. It would be wonderful if you could update the French translation. 

The string is the new description to the message field on the settings page and it reads:

`You can use basic HTML code in your message. Like &lt;strong&gt;, &lt;i&gt;, &lt;a&gt; and &lt;img&gt;`

**Comment by koudjdj** [comment]
French translation:
`Vous pouvez utiliser du code HTML de base dans votre message. Par exemple: &lt;strong&gt;, &lt;i&gt;, &lt;a&gt; et &lt;img&gt;`

**Comment by darkwhispering** [comment]
Would it be possible for you to update the translation files and do a new pull request to the develop branch? I do not have the tools to do this atm.

**Pull request merged**
